import express from 'express';
import cors from 'cors';
import multer from 'multer';
import crypto from 'crypto';
import fs from 'fs';
import path from 'path';
import {fileURLToPath} from 'url';
import dotenv from 'dotenv';
import {createServer} from 'http';
import {Server} from 'socket.io';

dotenv.config();
const __dirname=path.dirname(fileURLToPath(import.meta.url));
const ROOT=path.resolve(__dirname,'..');
const DATA_DIR=path.resolve(process.env.DATA_DIR||ROOT);
const DATA=path.join(DATA_DIR,'data.json');
const UPLOADS=path.join(DATA_DIR,'uploads');
fs.mkdirSync(UPLOADS,{recursive:true});
const ADMIN_EMAIL=String(process.env.ADMIN_EMAIL||'').trim().toLowerCase();
const ADMIN_PASSWORD=String(process.env.ADMIN_PASSWORD||'');
const SECRET=String(process.env.TOKEN_SECRET||'');
if(!/^\S+@\S+\.\S+$/.test(ADMIN_EMAIL)||ADMIN_PASSWORD.length<8||SECRET.length<32)throw new Error('Set ADMIN_EMAIL, an ADMIN_PASSWORD of at least 8 characters, and a TOKEN_SECRET of at least 32 characters.');
const empty={users:[],videos:[],messages:[],notifications:[],next:{user:1,video:1,message:1,notification:1}};
let db=fs.existsSync(DATA)?JSON.parse(fs.readFileSync(DATA,'utf8')):empty;
for(const k of Object.keys(empty)) if(db[k]===undefined) db[k]=empty[k];
if(!db.next) db.next=empty.next;
const save=()=>fs.writeFileSync(DATA,JSON.stringify(db,null,2));
const now=()=>new Date().toISOString();
const hashPassword=p=>{const salt=crypto.randomBytes(16).toString('hex');const hash=crypto.scryptSync(String(p),salt,64).toString('hex');return `scrypt:${salt}:${hash}`};
const verifyPassword=(p,stored)=>{try{const [,salt,hash]=String(stored).split(':');if(!salt||!hash)return false;const a=Buffer.from(hash,'hex');const b=crypto.scryptSync(String(p),salt,64);return a.length===b.length&&crypto.timingSafeEqual(a,b)}catch{return false}};
const tokenFor=id=>{const body=Buffer.from(JSON.stringify({id,exp:Date.now()+7*86400000})).toString('base64url');const sig=crypto.createHmac('sha256',SECRET).update(body).digest('base64url');return `${body}.${sig}`};
const userPublic=u=>({id:u.id,email:u.email,name:u.name,username:u.username,avatar:u.avatar||'',role:u.role,created_at:u.created_at});
const decodeToken=t=>{const [body,sig]=String(t||'').split('.');if(!body||!sig)return null;const expected=crypto.createHmac('sha256',SECRET).update(body).digest('base64url');if(sig.length!==expected.length||!crypto.timingSafeEqual(Buffer.from(sig),Buffer.from(expected)))return null;const p=JSON.parse(Buffer.from(body,'base64url').toString());return p.exp>Date.now()?p:null};
let admin=db.users.find(u=>u.email===ADMIN_EMAIL);
if(!admin){admin={id:db.next.user++,email:ADMIN_EMAIL,password:hashPassword(ADMIN_PASSWORD),name:'KRYNX Admin',username:'krynx_admin',avatar:'',role:'admin',created_at:now()};db.users.push(admin);save()}else{admin.role='admin';admin.password=hashPassword(ADMIN_PASSWORD);save()}

const app=express();const server=createServer(app);const io=new Server(server,{cors:{origin:process.env.CLIENT_URL||true,credentials:true}});
app.use(cors({origin:process.env.CLIENT_URL||true,credentials:true}));app.use(express.json({limit:'20mb'}));app.use('/uploads',express.static(UPLOADS));
const videoUpload=multer({storage:multer.diskStorage({destination:UPLOADS,filename:(r,f,cb)=>cb(null,`${Date.now()}-${crypto.randomBytes(5).toString('hex')}${path.extname(f.originalname)}`)}),limits:{fileSize:1024*1024*1024},fileFilter:(r,f,cb)=>cb(null,!!f.mimetype?.startsWith('video/'))});
const fileUpload=multer({storage:multer.diskStorage({destination:UPLOADS,filename:(r,f,cb)=>cb(null,`${Date.now()}-${crypto.randomBytes(5).toString('hex')}${path.extname(f.originalname)}`)}),limits:{fileSize:50*1024*1024}});
const auth=(req,res,next)=>{try{const p=decodeToken((req.headers.authorization||'').replace(/^Bearer\s+/i,''));const u=p&&db.users.find(x=>x.id===p.id);if(!u)throw 0;req.user=u;next()}catch{res.status(401).json({error:'Session expired. Please log in again.'})}};
const adminOnly=(req,res,next)=>req.user?.role==='admin'?next():res.status(403).json({error:'Admin access required'});
const notifyAdmins=(actorId,message,type='profile')=>{for(const u of db.users.filter(x=>x.role==='admin')){db.notifications.push({id:db.next.notification++,user_id:u.id,actor_id:actorId,type,message,created_at:now(),read_at:null})}save();io.emit('notification:new')};
const videoView=v=>({...v,uploader_name:db.users.find(u=>u.id===v.uploader_id)?.name||'Unknown',uploader_username:db.users.find(u=>u.id===v.uploader_id)?.username||'unknown',uploader_avatar:db.users.find(u=>u.id===v.uploader_id)?.avatar||''});
const messageView=m=>({...m,...(()=>{const u=db.users.find(x=>x.id===m.user_id)||{};return{name:u.name,username:u.username,avatar:u.avatar||'',role:u.role}})()});

app.get('/api/health',(req,res)=>res.json({ok:true,service:'KRYNX Video Vault',time:now()}));
app.post('/api/auth/register',(req,res)=>{try{const email=String(req.body.email||'').trim().toLowerCase(),password=String(req.body.password||''),name=String(req.body.name||'').trim(),username=String(req.body.username||'').trim().replace(/^@/,'').toLowerCase();if(!/^\S+@\S+\.\S+$/.test(email))return res.status(400).json({error:'Enter a valid email address.'});if(password.length<6)return res.status(400).json({error:'Password must be at least 6 characters.'});if(!name||name.length<2)return res.status(400).json({error:'Enter your full name.'});if(!/^[a-z0-9_.-]{3,20}$/.test(username))return res.status(400).json({error:'Username must be 3–20 characters: letters, numbers, _, ., -'});if(email===ADMIN_EMAIL)return res.status(400).json({error:'That email belongs to the admin account.'});if(db.users.some(u=>u.email===email))return res.status(409).json({error:'An account with this email already exists. Try Login.'});if(db.users.some(u=>u.username===username))return res.status(409).json({error:'That username is already taken.'});const u={id:db.next.user++,email,password:hashPassword(password),name,username,avatar:'',role:'user',created_at:now()};db.users.push(u);save();res.json({token:tokenFor(u.id),user:userPublic(u)})}catch(e){console.error(e);res.status(500).json({error:'Could not create account. Please try again.'})}});
app.post('/api/auth/login',(req,res)=>{try{const email=String(req.body.email||'').trim().toLowerCase(),password=String(req.body.password||'');const u=db.users.find(x=>x.email===email);if(!u||!verifyPassword(password,u.password))return res.status(401).json({error:'Wrong email or password. If you are new, create an account below.'});res.json({token:tokenFor(u.id),user:userPublic(u)})}catch(e){console.error(e);res.status(500).json({error:'Login service error. Check that the server is running.'})}});
app.get('/api/me',auth,(req,res)=>res.json(userPublic(req.user)));
app.put('/api/me',auth,(req,res)=>{const name=String(req.body.name||'').trim(),username=String(req.body.username||'').trim().replace(/^@/,'').toLowerCase(),avatar=String(req.body.avatar||'').trim();if(!name||!username)return res.status(400).json({error:'Name and username are required.'});if(db.users.some(u=>u.username===username&&u.id!==req.user.id))return res.status(409).json({error:'Username already taken.'});const old={...req.user};Object.assign(req.user,{name,username,avatar});save();if(old.name!==name)notifyAdmins(req.user.id,`@${old.username} changed name from “${old.name}” to “${name}”.`);if(old.username!==username)notifyAdmins(req.user.id,`A user changed username from @${old.username} to @${username}.`);if(old.avatar!==avatar)notifyAdmins(req.user.id,`@${username} changed their profile picture.`);res.json(userPublic(req.user))});
app.put('/api/me/password',auth,(req,res)=>{if(req.user.role==='admin')return res.status(403).json({error:'Admin password is controlled by the server.'});const {currentPassword,newPassword}=req.body;if(!verifyPassword(currentPassword,req.user.password))return res.status(400).json({error:'Current password is incorrect.'});if(String(newPassword||'').length<6)return res.status(400).json({error:'New password must be at least 6 characters.'});req.user.password=hashPassword(newPassword);save();notifyAdmins(req.user.id,`@${req.user.username} changed their password. Password values are never shown.`,'password');res.json({ok:true})});

app.get('/api/videos',auth,(req,res)=>res.json(db.videos.slice().sort((a,b)=>b.created_at.localeCompare(a.created_at)).map(videoView)));
app.post('/api/videos/upload',auth,(req,res)=>videoUpload.single('video')(req,res,async err=>{if(err)return res.status(400).json({error:err.code==='LIMIT_FILE_SIZE'?'Video exceeds the 1GB limit.':err.message});if(!req.file)return res.status(400).json({error:'Choose a video file first.'});const v={id:db.next.video++,title:String(req.body.title||req.file.originalname).trim(),description:String(req.body.description||''),source_type:'file',source:`/uploads/${req.file.filename}`,original_name:req.file.originalname,uploader_id:req.user.id,created_at:now()};db.videos.push(v);save();io.emit('video:new',videoView(v));res.json(videoView(v))}));
app.post('/api/videos/link',auth,(req,res)=>{try{const url=new URL(String(req.body.url||'').trim());if(!['http:','https:'].includes(url.protocol))return res.status(400).json({error:'Enter a valid http(s) URL.'});const v={id:db.next.video++,title:String(req.body.title||url.hostname).trim(),description:String(req.body.description||''),source_type:'link',source:url.toString(),original_name:'',uploader_id:req.user.id,created_at:now()};db.videos.push(v);save();io.emit('video:new',videoView(v));res.json(videoView(v))}catch{res.status(400).json({error:'Enter a valid http(s) URL.'})}});
app.delete('/api/videos/:id',auth,(req,res)=>{const id=Number(req.params.id),v=db.videos.find(x=>x.id===id);if(!v)return res.status(404).json({error:'Video not found.'});if(req.user.role!=='admin'&&v.uploader_id!==req.user.id)return res.status(403).json({error:'You can delete only your own videos.'});if(v.source_type==='file')fs.rmSync(path.join(UPLOADS,path.basename(v.source)),{force:true});db.videos=db.videos.filter(x=>x.id!==id);save();io.emit('video:deleted',id);res.json({ok:true})});
app.delete('/api/admin/videos/:id',auth,adminOnly,(req,res)=>{const id=Number(req.params.id),v=db.videos.find(x=>x.id===id);if(!v)return res.status(404).json({error:'Video not found.'});if(v.source_type==='file')fs.rmSync(path.join(UPLOADS,path.basename(v.source)),{force:true});db.videos=db.videos.filter(x=>x.id!==id);save();io.emit('video:deleted',id);res.json({ok:true})});

app.get('/api/chat/messages',auth,(req,res)=>res.json(db.messages.slice(-100).map(messageView)));
app.post('/api/chat/message',auth,(req,res)=>{const text=String(req.body.text||'').trim();if(!text)return res.status(400).json({error:'Message is empty.'});const m={id:db.next.message++,user_id:req.user.id,text,attachment_name:'',attachment_url:'',created_at:now()};db.messages.push(m);save();io.emit('chat:new',messageView(m));res.json(messageView(m))});
app.post('/api/chat/attachment',auth,(req,res)=>fileUpload.single('file')(req,res,err=>{if(err)return res.status(400).json({error:'Attachment is too large or invalid.'});if(!req.file)return res.status(400).json({error:'Choose a file.'});const m={id:db.next.message++,user_id:req.user.id,text:String(req.body.text||'').trim(),attachment_name:req.file.originalname,attachment_url:`/uploads/${req.file.filename}`,created_at:now()};db.messages.push(m);save();io.emit('chat:new',messageView(m));res.json(messageView(m))}));

app.get('/api/admin/stats',auth,adminOnly,(req,res)=>res.json({users:db.users.length,videos:db.videos.length,admins:db.users.filter(u=>u.role==='admin').length,messages:db.messages.length}));
app.get('/api/admin/users',auth,adminOnly,(req,res)=>res.json(db.users.map(u=>({...userPublic(u),video_count:db.videos.filter(v=>v.uploader_id===u.id).length}))));
app.post('/api/admin/users',auth,adminOnly,(req,res)=>{try{const email=String(req.body.email||'').trim().toLowerCase(),password=String(req.body.password||''),name=String(req.body.name||email.split('@')[0]||'').trim();if(!/^\S+@\S+\.\S+$/.test(email))return res.status(400).json({error:'Enter a valid email address.'});if(password.length<6)return res.status(400).json({error:'Password must be at least 6 characters.'});if(name.length<2)return res.status(400).json({error:'Name must be at least 2 characters.'});if(db.users.some(u=>u.email===email))return res.status(409).json({error:'An account with this email already exists.'});let username=String(req.body.username||email.split('@')[0]).trim().replace(/^@/,'').toLowerCase().replace(/[^a-z0-9_.-]/g,'').slice(0,20);if(username.length<3)return res.status(400).json({error:'Username must contain at least 3 valid characters.'});if(db.users.some(u=>u.username===username)){const base=username.slice(0,16);let suffix=1;while(db.users.some(u=>u.username===`${base}${suffix}`))suffix++;username=`${base}${suffix}`}const u={id:db.next.user++,email,password:hashPassword(password),name,username,avatar:'',role:'user',created_at:now()};db.users.push(u);save();res.status(201).json(userPublic(u))}catch(e){console.error(e);res.status(500).json({error:'Could not create account.'})}});
app.put('/api/admin/users/:id/password',auth,adminOnly,(req,res)=>{const u=db.users.find(x=>x.id===Number(req.params.id));if(!u)return res.status(404).json({error:'User not found.'});if(u.role==='admin')return res.status(403).json({error:'Admin passwords are managed by the server.'});const password=String(req.body.password||'');if(password.length<6)return res.status(400).json({error:'Password must be at least 6 characters.'});u.password=hashPassword(password);save();notifyAdmins(req.user.id,`Admin reset the password for @${u.username}. Password values are never shown.`,'password');res.json({ok:true})});
app.patch('/api/admin/users/:id/role',auth,adminOnly,(req,res)=>{const u=db.users.find(x=>x.id===Number(req.params.id));if(!u)return res.status(404).json({error:'User not found.'});if(u.id===req.user.id)return res.status(400).json({error:'You cannot change your own role.'});const role=req.body.role==='admin'?'admin':'user';u.role=role;save();notifyAdmins(req.user.id,`Admin changed @${u.username} to ${role}.`,'role');res.json(userPublic(u))});
app.delete('/api/admin/users/:id',auth,adminOnly,(req,res)=>{const id=Number(req.params.id);if(id===req.user.id)return res.status(400).json({error:'You cannot delete yourself.'});const u=db.users.find(x=>x.id===id);if(!u)return res.status(404).json({error:'User not found.'});for(const v of db.videos.filter(v=>v.uploader_id===id&&v.source_type==='file'))fs.rmSync(path.join(UPLOADS,path.basename(v.source)),{force:true});db.users=db.users.filter(x=>x.id!==id);db.videos=db.videos.filter(v=>v.uploader_id!==id);db.messages=db.messages.filter(m=>m.user_id!==id);save();res.json({ok:true})});
app.get('/api/notifications',auth,adminOnly,(req,res)=>res.json(db.notifications.filter(n=>n.user_id===req.user.id).sort((a,b)=>b.created_at.localeCompare(a.created_at)).slice(0,100)));

const online=new Map();io.on('connection',socket=>{socket.on('presence:join',u=>{if(!u?.id)return;online.set(u.id,{...u});io.emit('presence:list',[...online.values()])});socket.on('presence:leave',id=>{online.delete(Number(id));io.emit('presence:list',[...online.values()])});socket.on('disconnect',()=>{})});

app.use((err,req,res,next)=>{console.error(err);if(!res.headersSent)res.status(500).json({error:'Server error. Check the terminal for details.'})});
const dist=path.join(ROOT,'..','client','dist');if(fs.existsSync(dist)){app.use(express.static(dist));app.get('*',(req,res)=>{if(!req.path.startsWith('/api'))res.sendFile(path.join(dist,'index.html'))})}
const PORT=Number(process.env.PORT||5001);server.listen(PORT,'0.0.0.0',()=>console.log(`\nKRYNX Video Vault running on port ${PORT}\nPersistent data directory: ${DATA_DIR}\n`));
